# Generated by Django 4.2.5 on 2023-09-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
    ]
