# Generated by Django 4.2.5 on 2023-09-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProject', '0002_alter_producto_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuscarProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='IngresarProdcuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('codigo', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
