# Generated by Django 4.2.5 on 2023-09-09 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppProject', '0003_buscarproducto_ingresarprodcuto_delete_orden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buscarproducto',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppProject.producto'),
        ),
    ]
