# Generated by Django 4.2.4 on 2023-09-12 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppProject', '0006_alter_buscarproducto_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField()),
                ('fecha_entrega_esperada', models.DateField()),
                ('detalles', models.ManyToManyField(through='AppProject.DetallePedidoCompra', to='AppProject.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='buscarproducto',
            name='producto',
        ),
        migrations.DeleteModel(
            name='IngresarProdcuto',
        ),
        migrations.DeleteModel(
            name='BuscarProducto',
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProject.proveedor'),
        ),
        migrations.AddField(
            model_name='detallepedidocompra',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProject.pedidocompra'),
        ),
        migrations.AddField(
            model_name='detallepedidocompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProject.producto'),
        ),
    ]
